language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "GLvEYXvqvUstaRhJ0blmDfxdpHxJ7+lfqciliflZZUDha7LD1fF3aLPzQa5TP5o6MahKNWTAQSnSchoWEjU4DXUKCXqNOknUjJJFx8TD55hvwx40uZzgqD6EYPC/8zr36qe/5InRETYxAS+/8EgMHzL1phm4+KWadHX4T4Mq3as="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
