<?php

/*
 * This file is part of the Pops package.
 *
 * Copyright © 2011 Erin Millard
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'TestCase.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Object.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'ArrayAccess.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Callable.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Countable.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Iterator.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'IteratorAggregate.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Overload.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Stringable.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Documentation'.DIRECTORY_SEPARATOR.'Confusion.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Documentation'.DIRECTORY_SEPARATOR.'SeriousBusiness.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Documentation'.DIRECTORY_SEPARATOR.'UppercaseProxy.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Documentation'.DIRECTORY_SEPARATOR.'OutputEscaper.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Uppercase'.DIRECTORY_SEPARATOR.'Pops.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Uppercase'.DIRECTORY_SEPARATOR.'ProxyArray.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Uppercase'.DIRECTORY_SEPARATOR.'ProxyClass.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Uppercase'.DIRECTORY_SEPARATOR.'ProxyObject.php';
require __DIR__.DIRECTORY_SEPARATOR.'Eloquent'.DIRECTORY_SEPARATOR.'Pops'.DIRECTORY_SEPARATOR.'Test'.DIRECTORY_SEPARATOR.'Fixture'.DIRECTORY_SEPARATOR.'Uppercase'.DIRECTORY_SEPARATOR.'ProxyPrimitive.php';