var tree = [["Eloquent",,"",
                [["Pops","Eloquent\/Pops.html","",
                [["Exception","Eloquent\/Pops\/Exception.html","",
                [["InvalidTypeException","Eloquent\/Pops\/Exception\/InvalidTypeException.html"," < Exception",
                [        ]]        ]],["Safe","Eloquent\/Pops\/Safe.html","",
                [["SafeInterface","Eloquent\/Pops\/Safe\/SafeInterface.html","",
                [        ]],["SafeProxy","Eloquent\/Pops\/Safe\/SafeProxy.html"," < Proxy",
                [        ]],["SafeProxyArray","Eloquent\/Pops\/Safe\/SafeProxyArray.html"," < ProxyArray",
                [        ]],["SafeProxyClass","Eloquent\/Pops\/Safe\/SafeProxyClass.html"," < ProxyClass",
                [        ]],["SafeProxyObject","Eloquent\/Pops\/Safe\/SafeProxyObject.html"," < ProxyObject",
                [        ]],["SafeProxyPrimitive","Eloquent\/Pops\/Safe\/SafeProxyPrimitive.html"," < ProxyPrimitive",
                [        ]]        ]],["AbstractProxy","Eloquent\/Pops\/AbstractProxy.html","",
                [        ]],["AbstractTraversableProxy","Eloquent\/Pops\/AbstractTraversableProxy.html"," < AbstractProxy",
                [        ]],["Proxy","Eloquent\/Pops\/Proxy.html","",
                [        ]],["ProxyArray","Eloquent\/Pops\/ProxyArray.html"," < AbstractTraversableProxy",
                [        ]],["ProxyArrayInterface","Eloquent\/Pops\/ProxyArrayInterface.html","",
                [        ]],["ProxyClass","Eloquent\/Pops\/ProxyClass.html"," < AbstractProxy",
                [        ]],["ProxyClassInterface","Eloquent\/Pops\/ProxyClassInterface.html","",
                [        ]],["ProxyInterface","Eloquent\/Pops\/ProxyInterface.html","",
                [        ]],["ProxyObject","Eloquent\/Pops\/ProxyObject.html"," < AbstractTraversableProxy",
                [        ]],["ProxyObjectInterface","Eloquent\/Pops\/ProxyObjectInterface.html","",
                [        ]],["ProxyPrimitive","Eloquent\/Pops\/ProxyPrimitive.html"," < AbstractProxy",
                [        ]],["ProxyPrimitiveInterface","Eloquent\/Pops\/ProxyPrimitiveInterface.html","",
                [        ]],["TraversableProxyInterface","Eloquent\/Pops\/TraversableProxyInterface.html","",
                [        ]]        ]]        ]]        ]

