var tree = [["Eloquent",,"",
                [["Pops","Eloquent\/Pops.html","",
                [["Safe","Eloquent\/Pops\/Safe.html","",
                [["SafeInterface","Eloquent\/Pops\/Safe\/SafeInterface.html","",
                [        ]],["SafeProxy","Eloquent\/Pops\/Safe\/SafeProxy.html"," < Proxy",
                [        ]],["SafeProxyArray","Eloquent\/Pops\/Safe\/SafeProxyArray.html"," < ProxyArray",
                [        ]],["SafeProxyClass","Eloquent\/Pops\/Safe\/SafeProxyClass.html"," < ProxyClass",
                [        ]],["SafeProxyObject","Eloquent\/Pops\/Safe\/SafeProxyObject.html"," < ProxyObject",
                [        ]],["SafeProxyPrimitive","Eloquent\/Pops\/Safe\/SafeProxyPrimitive.html"," < ProxyPrimitive",
                [        ]]        ]],["Proxy","Eloquent\/Pops\/Proxy.html","",
                [        ]],["ProxyArray","Eloquent\/Pops\/ProxyArray.html","",
                [        ]],["ProxyClass","Eloquent\/Pops\/ProxyClass.html","",
                [        ]],["ProxyInterface","Eloquent\/Pops\/ProxyInterface.html","",
                [        ]],["ProxyObject","Eloquent\/Pops\/ProxyObject.html","",
                [        ]],["ProxyPrimitive","Eloquent\/Pops\/ProxyPrimitive.html","",
                [        ]]        ]]        ]]        ]

